"""kwaro analyzers: prover (generate a PoC / failing test for a candidate).

Locked decision L6 (PoC honesty + sandbox limits):
- Lifecycle: GENERATED -> COMPILED -> EXECUTED -> VERIFIED | UNVERIFIED.
- VERIFIED only if it runs AND triggers expected failure. UNVERIFIED never raises severity.
- Execution OFF by default; the prover here only GENERATES (writes a file), it never runs code.

v1: an offline placeholder that writes a minimal, clearly-labelled failing-test
skeleton. If a Provider is supplied, a model can overwrite it with a real exploit
(kept separate so the offline path needs zero deps and zero model).
"""
from __future__ import annotations

import os

from ..core.models import Finding, PocState


def generate_poc(f: Finding, out_dir: str, provider=None) -> str:
    """Generate a PoC file for a finding. Returns the path. Sets f.poc_state.

    L6: this only GENERATES a file; it never executes. poc_state stays GENERATED
    (offline) until a separate, sandbox-gated executor verifies it.
    """
    os.makedirs(out_dir, exist_ok=True)
    safe_id = f.rule_id.replace(".", "_").replace("/", "_")
    path = os.path.join(out_dir, f"poc_{safe_id}_{f.id[:8]}.txt")

    if provider is not None:
        # model-driven path: ask the provider for a concrete exploit/test.
        # Kept minimal; offline by default so this branch is opt-in BYOK.
        try:
            from ..core.providers.base import Message, ToolSpec
            resp = provider.complete(
                [Message(role="system", content="You write a short, safe PoC sketch for a security finding. No destructive code."),
                 Message(role="user", content=f"Write a minimal PoC for: {f.title} at {f.file}:{f.line_start}. Snippet: {f.snippet}")],
            )
            content = resp.message.content or ""
        except Exception:
            content = ""
        if content.strip():
            with open(path, "w") as fh:
                fh.write(f"# PoC for {f.title} ({f.rule_id}) at {f.file}:{f.line_start}\n")
                fh.write("# GENERATED by model; NOT executed. Review in a sandbox.\n")
                fh.write(content + "\n")
            f.poc_state = PocState.GENERATED
            f.poc_path = path
            return path

    # offline placeholder
    with open(path, "w") as fh:
        fh.write(f"# PoC placeholder for {f.title} ({f.rule_id})\n")
        fh.write(f"# Location: {f.file}:{f.line_start}\n")
        fh.write(f"# Severity: {f.severity.value} | CWE: {f.cwe}\n")
        fh.write(f"# Snippet: {f.snippet}\n")
        fh.write("# This is a GENERATED placeholder, NOT a working exploit.\n")
        fh.write("# L6: execution is OFF by default. Run untrusted PoCs only in a container/VM.\n")
    f.poc_state = PocState.GENERATED
    f.poc_path = path
    return path
